apiVersion: nais.io/v1
kind: Naisjob
metadata:
  labels:
    team: appsec
  name: reposnusern
  namespace: appsec
spec:
  image: "{{ image }}"
  schedule: "5 22 * * *"
  ttlSecondsAfterFinished: 300
  replicas:
    cpuThresholdPercentage: 90
  resources:
    limits:
      memory: "128Mi"
    requests:
      cpu: "10m"
      memory: "16Mi"
  observability:
    logging:
      destinations:
        - id: loki
  envFrom:
    - secret: reposnusern
  gcp:
    bigQueryDatasets:
      - name: appsec
        permission: READWRITE