apiVersion: nais.io/v1
kind: Naisjob
metadata:
  labels:
    team: appsec
  name: reposnusern
  namespace: appsec
spec:
  image: "{{ image }}"
  schedule: "5 22 * * *"
  ttlSecondsAfterFinished: 300
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  resources:
    limits:
      memory: "32Mi"
    requests:
      cpu: "10m"
      memory: "16Mi"
  liveness:
    initialDelay: 10
    path: health/live
  readiness:
    initialDelay: 10
    path: health/ready
  observability:
    logging:
      destinations:
        - id: loki
  envFrom:
    - secret: reposnusern
  gcp:
    bigQueryDatasets:
      - name: appsec
        permission: READWRITE