// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: ci_configs.sql

package storage

import (
	"context"
	"time"
)

const insertOrUpdateCIConfig = `-- name: InsertOrUpdateCIConfig :exec
INSERT INTO ci_configs (
  repo_id, hentet_dato, path, content
) VALUES (
  $1, $2, $3, $4
)
ON CONFLICT (repo_id, hentet_dato, path) DO UPDATE SET
  content = EXCLUDED.content
`

type InsertOrUpdateCIConfigParams struct {
	RepoID     int64
	HentetDato time.Time
	Path       string
	Content    string
}

func (q *Queries) InsertOrUpdateCIConfig(ctx context.Context, arg InsertOrUpdateCIConfigParams) error {
	_, err := q.db.ExecContext(ctx, insertOrUpdateCIConfig,
		arg.RepoID,
		arg.HentetDato,
		arg.Path,
		arg.Content,
	)
	return err
}
