// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: dependency_files.sql

package storage

import (
	"context"
)

const insertDependencyFile = `-- name: InsertDependencyFile :exec
INSERT INTO dependency_files (
  repo_id, path, content
) VALUES ($1, $2, $3)
`

type InsertDependencyFileParams struct {
	RepoID  int64
	Path    string
	Content string
}

func (q *Queries) InsertDependencyFile(ctx context.Context, arg InsertDependencyFileParams) error {
	_, err := q.db.ExecContext(ctx, insertDependencyFile, arg.RepoID, arg.Path, arg.Content)
	return err
}
