// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: dockerfiles.sql

package storage

import (
	"context"
)

const insertDockerfile = `-- name: InsertDockerfile :one
INSERT INTO dockerfiles (repo_id, full_name, path, content)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type InsertDockerfileParams struct {
	RepoID   int64
	FullName string
	Path     string
	Content  string
}

func (q *Queries) InsertDockerfile(ctx context.Context, arg InsertDockerfileParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, insertDockerfile,
		arg.RepoID,
		arg.FullName,
		arg.Path,
		arg.Content,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}
