// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: dockerfile_features.sql

package storage

import (
	"context"
	"database/sql"
)

const insertDockerfileFeatures = `-- name: InsertDockerfileFeatures :exec
INSERT INTO dockerfile_features (
  dockerfile_id, base_image, base_tag, uses_latest_tag,
  has_user_instruction, has_copy_sensitive, has_package_installs, uses_multistage
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertDockerfileFeaturesParams struct {
	DockerfileID       int32
	BaseImage          sql.NullString
	BaseTag            sql.NullString
	UsesLatestTag      sql.NullBool
	HasUserInstruction sql.NullBool
	HasCopySensitive   sql.NullBool
	HasPackageInstalls sql.NullBool
	UsesMultistage     sql.NullBool
}

func (q *Queries) InsertDockerfileFeatures(ctx context.Context, arg InsertDockerfileFeaturesParams) error {
	_, err := q.db.ExecContext(ctx, insertDockerfileFeatures,
		arg.DockerfileID,
		arg.BaseImage,
		arg.BaseTag,
		arg.UsesLatestTag,
		arg.HasUserInstruction,
		arg.HasCopySensitive,
		arg.HasPackageInstalls,
		arg.UsesMultistage,
	)
	return err
}
