// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: dockerfiles.sql

package storage

import (
	"context"
)

const insertDockerfile = `-- name: InsertDockerfile :exec
INSERT INTO dockerfiles (
    repo_id, full_name, content
) VALUES (?, ?, ?)
`

type InsertDockerfileParams struct {
	RepoID   int64
	FullName string
	Content  string
}

func (q *Queries) InsertDockerfile(ctx context.Context, arg InsertDockerfileParams) error {
	_, err := q.db.ExecContext(ctx, insertDockerfile, arg.RepoID, arg.FullName, arg.Content)
	return err
}
