// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package storage

type Dockerfile struct {
	ID       int64
	RepoID   int64
	FullName string
	Content  string
}

type Repo struct {
	ID           int64
	Name         string
	FullName     string
	Description  string
	Stars        int64
	Forks        int64
	Archived     bool
	Private      bool
	IsFork       bool
	Language     string
	SizeMb       float64
	UpdatedAt    string
	PushedAt     string
	CreatedAt    string
	HtmlUrl      string
	Topics       string
	Visibility   string
	License      string
	OpenIssues   int64
	LanguagesUrl string
}

type RepoLanguage struct {
	ID       int64
	RepoID   int64
	Language string
	Bytes    int64
}
