// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package storage

import (
	"database/sql"
	"time"
)

type CiConfig struct {
	ID         int32
	RepoID     int64
	HentetDato time.Time
	Path       string
	Content    string
}

type Dockerfile struct {
	ID         int32
	RepoID     int64
	HentetDato time.Time
	FullName   string
	Path       string
	Content    string
}

type DockerfileFeature struct {
	DockerfileID         int32
	HentetDato           time.Time
	BaseImage            sql.NullString
	BaseTag              sql.NullString
	UsesLatestTag        sql.NullBool
	HasUserInstruction   sql.NullBool
	HasCopySensitive     sql.NullBool
	HasPackageInstalls   sql.NullBool
	UsesMultistage       sql.NullBool
	HasHealthcheck       sql.NullBool
	UsesAddInstruction   sql.NullBool
	HasLabelMetadata     sql.NullBool
	HasExpose            sql.NullBool
	HasEntrypointOrCmd   sql.NullBool
	InstallsCurlOrWget   sql.NullBool
	InstallsBuildTools   sql.NullBool
	HasAptGetClean       sql.NullBool
	WorldWritable        sql.NullBool
	HasSecretsInEnvOrArg sql.NullBool
}

type Repo struct {
	ID            int64
	HentetDato    time.Time
	Name          string
	FullName      string
	Description   string
	Stars         int64
	Forks         int64
	Archived      bool
	Private       bool
	IsFork        bool
	Language      string
	SizeMb        float32
	UpdatedAt     string
	PushedAt      string
	CreatedAt     string
	HtmlUrl       string
	Topics        string
	Visibility    string
	License       string
	OpenIssues    int64
	LanguagesUrl  string
	ReadmeContent sql.NullString
	HasSecurityMd bool
	HasDependabot bool
	HasCodeql     bool
}

type RepoLanguage struct {
	ID         int32
	RepoID     int64
	HentetDato time.Time
	Language   string
	Bytes      int64
}

type SbomGithubPackage struct {
	ID         int32
	RepoID     int64
	HentetDato time.Time
	Name       string
	Version    sql.NullString
	License    sql.NullString
	Purl       sql.NullString
}
