// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: readmes.sql

package storage

import (
	"context"
)

const insertReadme = `-- name: InsertReadme :exec
INSERT INTO readmes (
  repo_id, content
) VALUES ($1, $2)
`

type InsertReadmeParams struct {
	RepoID  int64
	Content string
}

func (q *Queries) InsertReadme(ctx context.Context, arg InsertReadmeParams) error {
	_, err := q.db.ExecContext(ctx, insertReadme, arg.RepoID, arg.Content)
	return err
}
