// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: repo_security_features.sql

package storage

import (
	"context"
)

const insertSecurityFeatures = `-- name: InsertSecurityFeatures :exec
INSERT INTO repo_security_features (
  repo_id, has_security_md, has_dependabot, has_codeql
) VALUES ($1, $2, $3, $4)
`

type InsertSecurityFeaturesParams struct {
	RepoID        int64
	HasSecurityMd bool
	HasDependabot bool
	HasCodeql     bool
}

func (q *Queries) InsertSecurityFeatures(ctx context.Context, arg InsertSecurityFeaturesParams) error {
	_, err := q.db.ExecContext(ctx, insertSecurityFeatures,
		arg.RepoID,
		arg.HasSecurityMd,
		arg.HasDependabot,
		arg.HasCodeql,
	)
	return err
}
