// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: repos.sql

package storage

import (
	"context"
)

const insertRepo = `-- name: InsertRepo :exec
INSERT INTO repos (
    id, name, full_name, description, stars, forks,
    archived, private, is_fork, language, size_mb,
    updated_at, pushed_at, created_at, html_url,
    topics, visibility, license, open_issues, languages_url
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
`

type InsertRepoParams struct {
	ID           int64
	Name         string
	FullName     string
	Description  string
	Stars        int64
	Forks        int64
	Archived     bool
	Private      bool
	IsFork       bool
	Language     string
	SizeMb       float64
	UpdatedAt    string
	PushedAt     string
	CreatedAt    string
	HtmlUrl      string
	Topics       string
	Visibility   string
	License      string
	OpenIssues   int64
	LanguagesUrl string
}

func (q *Queries) InsertRepo(ctx context.Context, arg InsertRepoParams) error {
	_, err := q.db.ExecContext(ctx, insertRepo,
		arg.ID,
		arg.Name,
		arg.FullName,
		arg.Description,
		arg.Stars,
		arg.Forks,
		arg.Archived,
		arg.Private,
		arg.IsFork,
		arg.Language,
		arg.SizeMb,
		arg.UpdatedAt,
		arg.PushedAt,
		arg.CreatedAt,
		arg.HtmlUrl,
		arg.Topics,
		arg.Visibility,
		arg.License,
		arg.OpenIssues,
		arg.LanguagesUrl,
	)
	return err
}
