// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: repo_languages.sql

package storage

import (
	"context"
)

const insertRepoLanguage = `-- name: InsertRepoLanguage :exec
INSERT INTO repo_languages (
  repo_id, language, bytes
) VALUES ($1, $2, $3)
`

type InsertRepoLanguageParams struct {
	RepoID   int64
	Language string
	Bytes    int64
}

func (q *Queries) InsertRepoLanguage(ctx context.Context, arg InsertRepoLanguageParams) error {
	_, err := q.db.ExecContext(ctx, insertRepoLanguage, arg.RepoID, arg.Language, arg.Bytes)
	return err
}
